#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service single
prepare_service 0*-monitoring
SERVICE_NAME="db-backup"
output_off

call dbbackup_setup_mode
call dbbackup_container_init
call dbbackup_create_schedulers backup
call create_zabbix dbbackup4

liftoff
